In [108]:
import pandas as pd
train = pd.read_csv('data/hr_train.csv')
test = pd.read_csv('data/hr_test.csv')
train.head()

enrollee_id      city  city_development_index gender  \
0        30266   city_84                   0.698   Male   
1        13254   city_16                   0.910   Male   
2        31675   city_21                   0.624   Male   
3        30804  city_104                   0.924   Male   
4        18269  city_143                   0.740   Male   

       relevent_experience enrolled_university education_level  \
0   No relevent experience    Full time course     High School   
1  Has relevent experience       no_enrollment        Graduate   
2   No relevent experience    Full time course     High School   
3   No relevent experience       no_enrollment        Graduate   
4  Has relevent experience       no_enrollment        Graduate   

  major_discipline experience company_size company_type last_new_job  \
0              NaN          1      100-500      Pvt Ltd        never   
1             STEM         15        50-99      Pvt Ltd            1   
2              NaN          3          NaN          NaN        never   
3             Arts        >20          NaN          NaN            2   
4             STEM         12        50-99      Pvt Ltd            1   

   training_hours  target  
0              15     0.0  
1               4     0.0  
2              12     0.0  
3             258     1.0  
4               3     0.0

In [109]:
test.head()

enrollee_id      city  city_development_index  gender  \
0        23044  city_136                   0.897  Female   
1        29611   city_21                   0.624     NaN   
2        22483   city_21                   0.624     NaN   
3         2660  city_103                   0.920    Male   
4        29216   city_65                   0.802    Male   

       relevent_experience enrolled_university education_level  \
0   No relevent experience    Full time course         Masters   
1  Has relevent experience       no_enrollment        Graduate   
2  Has relevent experience       no_enrollment        Graduate   
3  Has relevent experience       no_enrollment         Masters   
4  Has relevent experience       no_enrollment        Graduate   

  major_discipline experience company_size    company_type last_new_job  \
0             STEM          8      100-500   Public Sector            1   
1             STEM         16          <10         Pvt Ltd           >4   
2             STEM          5       10000+         Pvt Ltd            1   
3             STEM        >20      100-500  Funded Startup           >4   
4             STEM         15          <10         Pvt Ltd           >4   

   training_hours  
0              35  
1             134  
2              92  
3               6  
4              61

In [110]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15326 entries, 0 to 15325
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   enrollee_id             15326 non-null  int64  
 1   city                    15326 non-null  object 
 2   city_development_index  15326 non-null  float64
 3   gender                  11750 non-null  object 
 4   relevent_experience     15326 non-null  object 
 5   enrolled_university     15012 non-null  object 
 6   education_level         14961 non-null  object 
 7   major_discipline        13045 non-null  object 
 8   experience              15272 non-null  object 
 9   company_size            10539 non-null  object 
 10  company_type            10383 non-null  object 
 11  last_new_job            14984 non-null  object 
 12  training_hours          15326 non-null  int64  
 13  target                  15326 non-null  float64
dtypes: float64(2), int64(2), object(10)
me

In [111]:
print(train['major_discipline'].unique())
print(train['experience'].unique())
print(train['company_size'].unique())
print(train['company_type'].unique())
print(train['last_new_job'].unique())

[nan 'STEM' 'Arts' 'Other' 'Business Degree' 'No Major' 'Humanities']
['1' '15' '3' '>20' '12' '2' '6' '13' '11' '5' '<1' '8' '4' '16' '7' '14'
 '17' '9' '10' '18' '19' nan '20']
['100-500' '50-99' nan '10000+' '500-999' '<10' '5000-9999' '1000-4999'
 '10/49']
['Pvt Ltd' nan 'Funded Startup' 'Early Stage Startup' 'Public Sector'
 'NGO' 'Other']
['never' '1' '2' '>4' '4' '3' nan]


In [112]:
train['major_discipline'] = train['major_discipline'].fillna('No Major')
test['major_discipline'] = train['major_discipline'].fillna('No Major')

import numpy as np
train['experience'] = train['experience'].replace(to_replace=[np.nan, '<1', '>20'], value = [0, 0, 21])
train['experience'] = train['experience'].astype(int)
test['experience'] = test['experience'].replace(to_replace =[np.nan, '<1', '>20'], value = [0, 0 ,21])
test['experience']= test['experience'].astype(int)

train['company_size'] = train['company_size'].replace(to_replace =[np.nan, '<10', '10/49', '50-99', '100-500', '500-999', '1000-4999', '5000-9999', '10000+'],
                                                      value =[0,1,2,3,4,5,6,7,8])
train['company_size']= train['company_size'].astype(int)
test['company_size'] = test['company_size'].replace(to_replace =[np.nan, '<10', '10/49', '50-99', '100-500', '500-999', '1000-4999', '5000-9999', '10000+'],
                                                      value =[0,1,2,3,4,5,6,7,8])
test['company_size']= test['company_size'].astype(int)

train['company_type'] = train['company_type'].fillna('Other')
test['company_type'] = test['company_type'].fillna('Other')

train['last_new_job'] = train['last_new_job'].replace(to_replace =[np.nan, 'never', '>4'], value =[0,0,5])
train['last_new_job']= train['last_new_job'].astype(int)
test['last_new_job'] = test['last_new_job'].replace(to_replace =[np.nan, 'never', '>4'], value =[0,0,5])
test['last_new_job']= test['last_new_job'].astype(int)

C:\Users\shiny\AppData\Local\Temp\ipykernel_21764\27244005.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train['company_size'] = train['company_size'].replace(to_replace =[np.nan, '<10', '10/49', '50-99', '100-500', '500-999', '1000-4999', '5000-9999', '10000+'],
C:\Users\shiny\AppData\Local\Temp\ipykernel_21764\27244005.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test['company_size'] = test['company_size'].replace(to_replace =[np.nan, '<10', '10/49', '50-99', '100-500', '500-999', '1000-4999', '5000-9999', '10000+

In [113]:
print(train['gender'].unique())

['Male' nan 'Other' 'Female']


In [114]:
train['gender']= train['gender'].map({'Male':1, 'Female':2, np.nan:0, 'Other':0})
test['gender']= test['gender'].map({'Male':1, 'Female':2, np.nan:0, 'Other':0})
print(train['gender'].unique())

[1 0 2]


In [115]:
# drop : enrollee_id, city
train_target = train['target']
train = train.drop(columns=['enrollee_id', 'city','target'])
test = test.drop(columns=['enrollee_id', 'city'])
train.head()

city_development_index  gender      relevent_experience  \
0                   0.698       1   No relevent experience   
1                   0.910       1  Has relevent experience   
2                   0.624       1   No relevent experience   
3                   0.924       1   No relevent experience   
4                   0.740       1  Has relevent experience   

  enrolled_university education_level major_discipline  experience  \
0    Full time course     High School         No Major           1   
1       no_enrollment        Graduate             STEM          15   
2    Full time course     High School         No Major           3   
3       no_enrollment        Graduate             Arts          21   
4       no_enrollment        Graduate             STEM          12   

   company_size company_type  last_new_job  training_hours  
0             4      Pvt Ltd             0              15  
1             3      Pvt Ltd             1               4  
2             0        Other             0              12  
3             0        Other             2             258  
4             3      Pvt Ltd             1               3

In [116]:
test.head()

city_development_index  gender      relevent_experience  \
0                   0.897       2   No relevent experience   
1                   0.624       0  Has relevent experience   
2                   0.624       0  Has relevent experience   
3                   0.920       1  Has relevent experience   
4                   0.802       1  Has relevent experience   

  enrolled_university education_level major_discipline  experience  \
0    Full time course         Masters         No Major           8   
1       no_enrollment        Graduate             STEM          16   
2       no_enrollment        Graduate         No Major           5   
3       no_enrollment         Masters             Arts          21   
4       no_enrollment        Graduate             STEM          15   

   company_size    company_type  last_new_job  training_hours  
0             4   Public Sector             1              35  
1             1         Pvt Ltd             5             134  
2             8         Pvt Ltd             1              92  
3             4  Funded Startup             5               6  
4             1         Pvt Ltd             5              61

In [117]:
train.isna().sum()

city_development_index      0
gender                      0
relevent_experience         0
enrolled_university       314
education_level           365
major_discipline            0
experience                  0
company_size                0
company_type                0
last_new_job                0
training_hours              0
dtype: int64

In [118]:
test.isna().sum()

city_development_index     0
gender                     0
relevent_experience        0
enrolled_university       72
education_level           95
major_discipline           0
experience                 0
company_size               0
company_type               0
last_new_job               0
training_hours             0
dtype: int64

In [119]:
print(train['enrolled_university'].unique())
print(test['enrolled_university'].unique())
print(train['education_level'].unique())
print(test['education_level'].unique())

['Full time course' 'no_enrollment' 'Part time course' nan]
['Full time course' 'no_enrollment' 'Part time course' nan]
['High School' 'Graduate' 'Masters' nan 'Primary School' 'Phd']
['Masters' 'Graduate' 'High School' nan 'Phd' 'Primary School']


In [120]:
train['enrolled_university']= train['enrolled_university'].fillna('no_enrollment')
train['enrolled_university']= train['enrolled_university'].replace([np.nan], ['no_enrollment'])
test['enrolled_university']= test['enrolled_university'].fillna('no_enrollment')
test['enrolled_university']= test['enrolled_university'].replace([np.nan], ['no_enrollment'])
train['enrolled_university']= train['enrolled_university'].map({'no_enrollment':0, 'Part time course':1, 'Full time course':2})
test['enrolled_university']= test['enrolled_university'].map({'no_enrollment':0, 'Part time course':1, 'Full time course':2})
# train['enrolled_university']= train['enrolled_university'].astype(int)
# test['enrolled_university']= test['enrolled_university'].astype(int)

train['education_level'] = train['education_level'].fillna('Graduate') # on average,
test['education_level'] = test['education_level'].fillna('Graduate')
train['education_level']= train['education_level'].replace([np.nan], ['Graduate'])
test['education_level']= test['education_level'].replace([np.nan], ['Graduate'])
train['education_level'] = train['education_level'].map({'Primary School':0, 'High School':1, 'Graduate':2, 'Masters':3, 'Phd':4})
test['education_level'] = test['education_level'].map({'Primary School':0, 'High School':1, 'Graduate':2, 'Masters':3, 'Phd':4})
# train['education_level']= train['education_level'].astype(int)
# test['education_level']= test['education_level'].astype(int)

In [121]:
print(train['enrolled_university'].unique())
print(test['enrolled_university'].unique())
print(train['education_level'].unique())
print(test['education_level'].unique())

[2 0 1]
[2 0 1]
[1 2 3 0 4]
[3 2 1 4 0]


In [122]:
train['enrolled_university']= train['enrolled_university'].astype(int)
test['enrolled_university']= test['enrolled_university'].astype(int)
train['education_level']= train['education_level'].astype(int)
test['education_level']= test['education_level'].astype(int)

In [123]:
train.head()

city_development_index  gender      relevent_experience  \
0                   0.698       1   No relevent experience   
1                   0.910       1  Has relevent experience   
2                   0.624       1   No relevent experience   
3                   0.924       1   No relevent experience   
4                   0.740       1  Has relevent experience   

   enrolled_university  education_level major_discipline  experience  \
0                    2                1         No Major           1   
1                    0                2             STEM          15   
2                    2                1         No Major           3   
3                    0                2             Arts          21   
4                    0                2             STEM          12   

   company_size company_type  last_new_job  training_hours  
0             4      Pvt Ltd             0              15  
1             3      Pvt Ltd             1               4  
2             0        Other             0              12  
3             0        Other             2             258  
4             3      Pvt Ltd             1               3

In [124]:
print(train.shape, test.shape)

combined = pd.concat([train, test])
combined = pd.get_dummies(combined)

train = combined[:len(train)]
test = combined[-len(test):]

print(train.shape, test.shape)

(15326, 11) (3832, 11)
(15326, 22) (3832, 22)


In [125]:
from sklearn.model_selection import train_test_split
train_input, val_input, train_target_2, val_target = train_test_split(train, train_target)

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(train_input, train_target_2)
print(rf.score(train_input, train_target_2), rf.score(val_input, val_target))

0.9986079693753263 0.784446764091858


In [127]:
pred = rf.predict_proba(test)
submit = pd.DataFrame({'pred':pred[:,1]})
submit.head()

pred
0  0.33
1  0.42
2  0.47
3  0.13
4  0.13

In [128]:
submit.to_csv('6_binary_regression_turnover.csv', index=False)